---
title: "Untitled"
output: html_document
---
```{r}
library(FSA)
library(FSAdata)
library(nlstools)
```

```{r}
data(WalleyeEL)
WalleyeEL$logage0 <- log(WalleyeEL$age0)
rckr <- srFuns(type="Ricker")
svR <- srStarts(age0~age5,data=WalleyeEL,type="Ricker")
## Additive
srR <- nls(age0~rckr(age5,a,b),data=WalleyeEL,start=svR)
bootR <- nlsBoot(srR)
cbind(estimates=coef(srR),confint(srR),confint(bootR))
## Multiplicative
srR2 <- nls(logage0~log(rckr(age5,a,b)),data=WalleyeEL,start=svR)
bootR2 <- nlsBoot(srR2)
cbind(estimates=coef(srR2),confint(srR2),confint(bootR2))

mnS <- mean(WalleyeEL$age5)
rckr(mnS,a=coef(srR))
rckr(mnS,a=coef(srR2))

```

```{r}
ind <- srFuns(type="independence")
svI <- srStarts(age0~age5,data=WalleyeEL,type="independence")
srI <- nls(age0~ind(age5,a),data=WalleyeEL,start=svI)
srI2 <- nls(logage0~log(ind(age5,a)),data=WalleyeEL,start=svI)
c(estimates=coef(srI),confint(srI))
c(estimates=coef(srI2),confint(srI2))

lmI <- lm(age0~0+age5,data=WalleyeEL)
c(estimates=coef(lmI),confint(lmI))

ind(mnS,a=coef(srI))
ind(mnS,a=coef(srI2))
#bootI <- nlsBoot(srI)
```

```{r}
x <- seq(0,3000,length.out=499)     # many S for prediction
pRR <- rckr(x,a=coef(srR))          # predicted mean R for Ricker
pIR <- ind(x,a=coef(srI))           # predicted mean R for independence model
LCIR <- UCIR <- LCII <- UCII <- numeric(length(x))

for(i in 1:length(x)) {             # CIs for mean R @ each S
  tmp <- apply(bootR$coefboot,MARGIN=1,FUN=rckr,S=x[i])
  LCIR[i] <- quantile(tmp,0.025)
  UCIR[i] <- quantile(tmp,0.975)
  tmp <- predict(lmI,data.frame(age5=x[i]),interval="confidence")
  LCII[i] <- tmp[1,"lwr"]
  UCII[i] <- tmp[1,"upr"]
}
ylmts <- range(c(pRR,LCIR,UCIR,pIR,LCII,UCII,WalleyeEL$age0))
xlmts <- range(c(x,WalleyeEL$age5))

plot(age0~age5,data=WalleyeEL,xlim=xlmts,ylim=ylmts,col="white",
     ylab="Age-0 Walleye",xlab="Age-5 Walleye")
polygon(c(x,rev(x)),c(LCII,rev(UCII)),col=rgb(0,0,0,1/10),border=NA)
polygon(c(x,rev(x)),c(LCIR,rev(UCIR)),col=rgb(0,0,0,1/3),border=NA)

points(age0~age5,data=WalleyeEL,pch=19)
lines(pRR~x,lwd=2)
lines(pIR~x,lwd=2,lty=2)
```

```{r}
meanS <- mean(WalleyeEL$age5)
tmp <- apply(bootR$coefboot,MARGIN=1,FUN=rckr,S=meanS)
c(rckr(meanS,a=coef(srR)),quantile(tmp,c(0.025,0.975)))
predict(lmI,data.frame(age5=meanS),interval="confidence")
```

```{r}
extraSS(srI,com=srR)
extraSS(srI2,com=srR2)
```

