library(NCStats)
ff <- read.table("http://www.ncfaculty.net/dogle/R/Data_Master/R/FlyingFox1.txt",header=TRUE)
str(ff)
ff$sex <- factor(ff$sex,levels=c("young","male","female"))
table(ff$sex)
lm1 <- lm(body.mass~forearm.len*sex,data=ff)
trans.chooser(lm1,show.stats=TRUE)
anova(lm1)
comp.slopes(lm1)
comp.intercepts(lm1)
fit.plot(lm1,legend="topleft",col="gray")
predict(lm1,data.frame(forearm.len=c(155,155,155),sex=c("young","male","female")))

ff$log.bm <- log(ff$body.mass)
ff$log.fl <- log(ff$forearm.len)
lm2 <- lm(log.bm~log.fl*sex,data=ff)
anova(lm2)
comp.slopes(lm2)
comp.intercepts(lm2)
fit.plot(lm2,legend="topleft",col="gray")
predict(lm2,data.frame(log.fl=c(5.04,5.04,5.04),sex=c("young","male","female")))
