library(NCStats)
d <- read.table("http://www.ncfaculty.net/dogle/R/Data_Master/R/DoseResponse.txt",header=TRUE)
d$dose <- factor(d$dose)
str(d)
windows(5,5)
par(mar=c(3.5,3.5,1,1),mgp=c(2,0.75,0))
lm1 <- lm(mort~dose,data=d)
anova(lm1)
fitPlot(lm1)
leveneTest(lm1)
residPlot(lm1)
adTest(lm1$residuals)
hist(lm1$residuals,main="")
outlierTest(lm1)

library(multcomp)
m <- read.table("http://www.ncfaculty.net/dogle/R/Data_Master/R/MooseBrowse.txt",header=TRUE)
str(m)
lm2 <- lm(height~treat,data=m)
anova(lm2)
m.mc <- glht(lm2,mcp(treat="Tukey"))
summary(m.mc)
confint(m.mc)
fitPlot(lm2)
