library(NCStats)
d <- read.table("RedSnapper.txt",header=TRUE)
str(d)
lm1 <- lm(volume~pressure,data=d)
transChooser(lm1)
anova(lm1)
summary(lm1)
mc1 <- glht(lm1,mcp(pressure="Tukey"))
summary(mc1)
confint(mc1)

d$logvol <- log(d$volume)
lm2 <- lm(logvol~pressure,data=d)
anova(lm2)
summary(lm2)
mc2 <- glht(lm2,mcp(pressure="Tukey"))
summary(mc2)
( ci2 <- confint(mc2) )
exp(ci2$confint)


par(mar=c(3,3,0.1,0.1),mgp=c(2,0.5,0))
fitPlot(lm1,xlab="Pressure",ylab="",pch=0,col="white",interval=FALSE,main="",xaxt="n",yaxt="n")
axis(1,1:4,c("Control","","",""))
axis(2,seq(20,60,10),c("","","","",""))