library(NCStats)
library(multcomp)
setwd("C:/aaaWork/Class Materials/MTH207/Year_Specific/W13/Assessments")

### TWO-WAY ANOVA
d75 <- read.table("box7_5.txt",header=TRUE)
d75$Month <- factor(d75$Month,levels=c("Jun","Aug"))
d75$Depth <- factor(d75$Depth)
d75$comb <- d75$Month:d75$Depth
str(d75)
lm1 <- lm(CPE~Month*Depth,data=d75)
transChooser(lm1)
anova(lm1)
mc1a <- glht(lm1,mcp(Month="Tukey"))
confint(mc1a)
mc1b <- glht(lm1,mcp(Depth="Tukey"))
confint(mc1b)
lm2 <- lm(CPE~comb,data=d75)
mc2 <- glht(lm1a,mcp(comb="Tukey"))
glhtSig(mc2)
fitPlot(lm1,which="Month",ylim=c(0,45),main="")
fitPlot(lm1,which="Depth",ylim=c(0,45),main="")
fitPlot(lm1,change.order=TRUE,ylim=c(-20,80),main="")

d75$tCPE <- d75$CPE^(0.5)
lm3 <- lm(tCPE~Month*Depth,data=d75)
anova(lm3)
mc3a <- glht(lm3,mcp(Month="Tukey"))
confint(mc3a)
mc3b <- glht(lm3,mcp(Depth="Tukey"))
confint(mc3b)
lm4 <- lm(CPE~comb,data=d75)
mc4 <- glht(lm4,mcp(comb="Tukey"))
glhtSig(mc4)
fitPlot(lm3,which="Month",ylim=c(0,7),main="")
fitPlot(lm3,which="Depth",ylim=c(0,7),main="")
fitPlot(lm3,change.order=TRUE,ylim=c(-2,10),main="")

# tighter graphics
windows(4,4); par(mar=c(3,3,0.5,0.5),mgp=c(2,0.4,0),tcl=-0.1)
fitPlot(lm1,which="Month",ylim=c(0,45),main="")
fitPlot(lm1,which="Depth",ylim=c(0,45),main="")
fitPlot(lm1,change.order=TRUE,ylim=c(-20,80),main="")

fitPlot(lm3,which="Month",ylim=c(0,7),main="")
fitPlot(lm3,which="Depth",ylim=c(0,7),main="")
fitPlot(lm3,change.order=TRUE,ylim=c(-2,10),main="")

### SLR
kr <- read.table("KempsRidley.txt",header=TRUE)
str(kr)
lm5 <- lm(wt~scl,data=kr)
transChooser(lm5)
summary(lm5)
confint(lm5)
predict(lm5,data.frame(scl=40),interval="prediction")
predict(lm5,data.frame(scl=40),interval="confidence")

kr$logwt <- log(kr$wt)
lm6 <- lm(logwt~scl,data=kr)
summary(lm6)
confint(lm6)
predict(lm6,data.frame(scl=40),interval="prediction")
predict(lm6,data.frame(scl=40),interval="confidence")

kr$logscl <- log(kr$scl)
lm7 <- lm(logwt~logscl,data=kr)
summary(lm7)
confint(lm7)
predict(lm7,data.frame(logscl=log(40)),interval="prediction")
predict(lm7,data.frame(logscl=log(40)),interval="confidence")