---
layout: page
title: Mortality
subtitle: Class Exercise
author: Derek H. Ogle
css: /css/modules.css
output:
  html_document:
    self_contained: no
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCNRS349/modules/Mortality/")
source("../../rhelpers/rhelpers.R")
fnm <- "CE1"
modHTML(fnm)
```

```{r echo=FALSE, results='hide', message=FALSE}
library(FSAsim)
fnm <- "CE1"
source("../../rhelpers/knitr_setup.R")
set.seed(13797834)
```

----

## Understanding the Shape of Catch Curves

#### Background

Estimating the mortality rate for a population of fish is a key component to estimating safe harvest levels for many fisheries.  Mortality rates can be estimated with a variety of analytical methods but a very common method is the "catch curve" method.  In its simplest form, the catch curve method uses the descending trend in log abundance-at-age versus age to estimate the instantaneous mortality rate ($Z$).
  
#### Simulation Description

The `catchCurveSim()` function in the `FSAsim` package can be used to evaluate the effect of parameter values and assumption violations on the "shape" of the catch curve.  This function works by creating several cohorts of fish with values of $N_{0}$ and $Z$ that are supplied by the user.  These cohorts are then projected into the future (i.e., the $Z$ is applied to $N_0$ for a certain age) and a sample of the population in a given year is taken.  The user can make choices to modify aspects of the simulation to understand how the catch-curve plot and the estimate of $Z$ are effected.

The `catchCurveSim()` function has the following arguments:

* `max.age=` the maximum age to model in the simulation (default is 15).
* `deltaAge=` the age at which the the mortality rate and initial population size multiplier takes effect (see below).
* `recruit.age=` the age for which the population of fish is fully recruited to the gear.  This will correspond to the age at the peak log abundance of the catch curve.

After calling the function, a plot will appear with three lines that connect points of log catch at age data.  Three lines may not be apparent as they may be plotted on top of each other.  The gray line is the catch curve at the initial or default values of the simulation ($Z=0.4$ and $N_{0}$=700 with no assumption violations).  This line is provided simply as a reference.  The red line is the catch curve for the current values of $Z$ and $N_{0}$ selected by the user (see below) but ignoring any assumption violations modeled by the user.  Finally, the blue line is the catch curve created by all choices made by the user, including changes to $Z$ and $N_{0}$ and any values that simulate assumption violations.  The blue line is plotted after (or on top) of the red line which is after the gray line.


```{r fig.width=5,fig.height=4}
catchCurveSim()
```

In RStudio, this plot will have a gear icon in the upper-left corner that will open a dialog box that allows you to change the following items in the simulation.

* `Z mean` - the mean $Z$ to use in the simulations.  If `Z CV` (see below) is set to 0, then this is the exact $Z$ used in the simulations.
* `No mean` - the mean $N_{0}$ to use in the simulations.  If `No CV' (see below) is set to 0 then this is the exact $N_{0}$ used in the simulations.

Changing these two values allows the user to see the effect of increasing or decreasing values of $Z$ or $N_{0}$ on the shape of the catch curve.  Changing only these two sliders does not model assumption violations.

----

#### Questions I

1. How does the descending limb of the catch curve change in each situation below.
    1. Increase mean $Z$.
    1. Decrease mean $Z$.
    1. Increase mean $N_{0}$.
    1. Decrease mean $N_{0}$.

----

<div class="text-center">
<ul class="pagination pagination-lg">
  <li><a href="../index.html">^</a></li>
  <li class="active"><a href="#">1</a></li>
  <li><a href="CE1b.html">2</a></li>
</ul>
