---
layout: page
title: Effects of Angling on a Previously Unexploited Wisconsin Fish Community
author: Derek H. Ogle
css: /css/modules.css
output:
  html_document:
    self_contained: no
---

```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/NCNRS349/modules/CEX/")
source("../../rhelpers/rhelpers.R")
modHTML("SizeStructure2_CEX2")
```

```{r echo=FALSE, results='hide', message=FALSE}
source("../../rhelpers/knitr_setup.R")
```

----

## Analysis & Interpretation Questions II
Length- and age-frequency plots, as well as proportional size distribution of quality- (PSD), preferred- (PSD-P), and memorable-length fish, for Bluegill, Pumpkinseed, Yellow Perch, and Largemouth Bass from the **POST-ANGLING** period are shown below.

```{r fig.width=7.5, fig.height=15, echo=FALSE, message=FALSE, warning=FALSE}
library(FSA)
library(tidyverse)
library(ggplot2)
library(patchwork)

d <- read.csv("https://raw.githubusercontent.com/droglenc/NCNRS349/gh-pages/modules/RESOURCES/GoeddeCobleData.csv") %>%
  mutate(species=plyr::mapvalues(species,
                                 from=c("BLG","LMB","PKS","YEP","NOP"),
                                 to=c("Bluegill","Largemouth Bass",
                                      "Pumpkinseed","Yellow Perch",
                                      "Northern Pike")),
         gcat=psdAdd(len,species),
         species=factor(species,levels=c("Bluegill","Pumpkinseed","Yellow Perch",
                                         "Largemouth Bass","Northern Pike")))

clrs <- c(substock="white",stock="gray80",quality="gray60",preferred="gray40",
          memorable="gray20",trophy="gray10")

tmp1 <- droplevels(filter(d,period=="post"))
tmp2 <- droplevels(filter(tmp1,gcat!="substock"))

tbl <- xtabs(~species+gcat,data=tmp2)
iPSDs <- prop.table(tbl,margin=1)*100
PSDs <- t(apply(iPSDs,MARGIN=1,FUN=rcumsum))
lPSDs <- as.data.frame(PSDs) %>%
  select(-stock) %>%
  mutate(lbl=paste0("PSD-Q=",formatC(quality,format="f",digits=0),"\n",
                    "PSD-P=",formatC(preferred,format="f",digits=0),"\n",
                    "PSD-M=",formatC(memorable,format="f",digits=0)))

bg_l_post <- ggplot(data=filter(tmp1,species=="Bluegill"),
                   mapping=aes(x=len,fill=gcat)) +
  geom_histogram(binwidth=10,boundary=0,color="black") +
  scale_x_continuous(name="Total Length (mm)",limits=c(0,NA),
                     expand=expansion(mult=0.01)) +
  scale_y_continuous(name="Frequency",expand=expansion(mult=c(0,0.03))) +
  scale_fill_manual(values=clrs) +
  theme_bw() +
  theme(legend.position="none") +
  labs(title="Bluegill Post-Angling")

bg_l_post2 <- bg_l_post +
  annotate(geom="label",x=-Inf,y=Inf,hjust=-0.05,vjust=1.05,
           label=lPSDs["Bluegill","lbl"])

bg_a_post <- ggplot(data=filter(tmp1,species=="Bluegill"),
                   mapping=aes(x=age)) +
  geom_histogram(binwidth=1,boundary=0,color="black") +
  scale_x_continuous(name="Age (years)",breaks=seq(0,15,1)) +
  scale_y_continuous(name="Frequency",expand=expansion(mult=c(0,0.03))) +
  theme_bw() +
  theme(panel.grid.minor.x=element_blank())

pks_l_post <- bg_l_post %+% filter(tmp1,species=="Pumpkinseed") +
  labs(title="Pumpkinseed Post-Angling")
pks_l_post2 <- pks_l_post +
  annotate(geom="label",x=-Inf,y=Inf,hjust=-0.05,vjust=1.05,
           label=lPSDs["Pumpkinseed","lbl"])
pks_a_post <- bg_a_post %+% filter(tmp1,species=="Pumpkinseed")

yp_l_post <- bg_l_post %+% filter(tmp1,species=="Yellow Perch") +
  labs(title="Yellow Perch Post-Angling")
yp_l_post2 <- yp_l_post +
  annotate(geom="label",x=-Inf,y=Inf,hjust=-0.05,vjust=1.05,
           label=lPSDs["Yellow Perch","lbl"])
yp_a_post <- bg_a_post %+% filter(tmp1,species=="Yellow Perch")

lmb_l_post <- bg_l_post %+% filter(tmp1,species=="Largemouth Bass") +
  geom_histogram(binwidth=25,boundary=0,color="black") +
  labs(title="Largemouth Bass Post-Angling")
lmb_l_post2 <- lmb_l_post +
  annotate(geom="label",x=-Inf,y=Inf,hjust=-0.05,vjust=1.05,
           label=lPSDs["Largemouth Bass","lbl"])
lmb_a_post <- bg_a_post %+% filter(tmp1,species=="Largemouth Bass")

nop_l_post <- lmb_l_post %+% filter(tmp1,species=="Northern Pike") +
  labs(title="Northern Pike Post-Angling")
nop_l_post2 <- nop_l_post +
  annotate(geom="label",x=-Inf,y=Inf,hjust=-0.05,vjust=1.05,
           label=lPSDs["Northern Pike","lbl"])

(bg_l_post2 + bg_a_post) / (pks_l_post2 + pks_a_post) / (yp_l_post2 + yp_a_post) / (lmb_l_post2 + lmb_a_post)
```

Use these results to answer the following questions.

<ol start="5">
<li>Assess the length- and age-frequency histograms for Bluegill, Pumpkinseed, Yellow Perch, and Largemouth Bass from Mid Lake after angler exploitation was allowed.</li>
<li>Write a clear paragraph, for each species, that compares the pre- and post-angling size- and age-structure results.</li>
<li>How did your summaries from the previous question compare to your expectations from before seeing the post-angling results?  Suggest possible reasons for any differences.</li>
<li>How do you suppose the annual mortality rate differed between the two periods for each species?  Use specific evidence to support your supposition.</li>
</ol>

&nbsp;

----

<div class="text-center">
<ul class="pagination pagination-lg">
  <li><a href="index.html">^</a></li>
  <li><a href="SizeStructure2_CEX1.html">1</a></li>
  <li class="active"><a href="#">2</a></li>
</ul>
